# Generated by Django 3.2.9 on 2022-05-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phoneno', models.IntegerField()),
                ('email', models.EmailField(max_length=60)),
            ],
        ),
    ]
